/**
 * Product Configurations Registry
 * 9 Main Categories → Sub-products
 * Each sub-product has: sources, merge steps, comparison columns
 */

// ─── CATEGORY DEFINITIONS ───
export const CATEGORIES = [
  { id: 'aeps', name: 'AEPS', icon: '🖐️', color: '#f59e0b', desc: 'Aadhaar Enabled Payment System' },
  { id: 'matm', name: 'MATM', icon: '💳', color: '#ef4444', desc: 'Micro ATM' },
  { id: 'imps', name: 'IMPS', icon: '⚡', color: '#8b5cf6', desc: 'Immediate Payment Service' },
  { id: 'bbps', name: 'BBPS', icon: '🧾', color: '#06b6d4', desc: 'Bharat Bill Payment System' },
  { id: 'recharge', name: 'RECHARGE', icon: '📱', color: '#10b981', desc: 'Mobile & DTH Recharge' },
  { id: 'upi', name: 'UPI', icon: '📲', color: '#3b82f6', desc: 'Unified Payments Interface' },
  { id: 'dmt', name: 'DMT', icon: '💸', color: '#ec4899', desc: 'Direct Money Transfer' },
  { id: 'pos', name: 'POS / Cashpoint', icon: '🏪', color: '#14b8a6', desc: 'Point of Sale' },
  { id: 'cashout', name: 'RBL CASHOUT/PAYOUT', icon: '🏦', color: '#f97316', desc: 'Wallet to Bank Cashout' },
];

// ─── SUB-PRODUCT CONFIGURATIONS ───
export const PRODUCTS = [

  // ═══════════════════════════════════════════
  // CATEGORY: AEPS
  // ═══════════════════════════════════════════

  {
    id: 'aadharpay',
    name: 'Aadharpay',
    category: 'aeps',
    apiEndpoint: '/adharpayandfinoaepsrecon',
    bucket: 'prod-isurecon',
    folder: 'a_pay-and-fino_aeps',
    sources: [
      { key: 'bank', label: 'Finobank File', required: true },
      { key: 'internal', label: 'Aadharpay Internal File', required: true },
      { key: 'wallet', label: 'Aadharpay Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge Bank & Internal',
        leftSource: 'bank',
        rightSource: 'internal',
        leftSuffix: '_bank_apay',
        rightSuffix: '_apay',
        mergeKey: 'Client_Txn_Id',
        leftMergeCol: 'Client_Txn_Id',
        rightMergeCol: 'Client_Txn_Id',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'Txn_Amount_bank_apay', rightCol: 'amountTransacted_apay', label: 'Txn_Amount' },
          { leftCol: 'Txn_status_bank_apay', rightCol: 'Status_apay', label: 'Txn_Status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'Client_Txn_Id',
        rightMergeCol: 'Client_Txn_Id',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'Txn_Amount_bank_apay', rightCol: 'amountTransacted_wallet', label: 'Txn_Amount' },
          { leftCol: 'Txn_status_bank_apay', rightCol: 'Status_wallet', label: 'Txn_Status' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'finoaadharpaymatch',
    outputMismatchFile: 'finoaadharpaymismatch',
    finalStatusCol: 'final_status_wallet',
  },

  {
    id: 'finoaeps',
    name: 'Fino AEPS',
    category: 'aeps',
    apiEndpoint: '/adharpayandfinoaepsrecon',
    bucket: 'prod-isurecon',
    folder: 'a_pay-and-fino_aeps',
    sources: [
      { key: 'bank', label: 'Finobank File', required: true },
      { key: 'internal', label: 'Fino Internal File', required: true },
      { key: 'wallet', label: 'Fino Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge Bank & Internal',
        leftSource: 'bank',
        rightSource: 'internal',
        leftSuffix: '_bank_aeps',
        rightSuffix: '_aeps',
        mergeKey: 'Client_Txn_Id',
        leftMergeCol: 'Client_Txn_Id',
        rightMergeCol: 'Client_Txn_Id',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'Txn_Amount_bank_aeps', rightCol: 'amountTransacted_aeps', label: 'Txn_Amount' },
          { leftCol: 'Txn_status_bank_aeps', rightCol: 'Status_aeps', label: 'Txn_Status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'Client_Txn_Id',
        rightMergeCol: 'Client_Txn_Id',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'Txn_Amount_bank_aeps', rightCol: 'amountTransacted_wallet', label: 'Txn_Amount' },
          { leftCol: 'Txn_status_bank_aeps', rightCol: 'Status_wallet', label: 'Txn_Status' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'finoaepsmatch',
    outputMismatchFile: 'finoaepsmismatch',
    finalStatusCol: 'final_status_wallet',
  },

  {
    id: 'nsdlaeps',
    name: 'NSDL AEPS',
    category: 'aeps',
    apiEndpoint: '/nsdlaepsrecon',
    bucket: 'prod-isurecon',
    folder: 'nsdlaeps',
    sources: [
      { key: 'npci', label: 'NSDL AEPS NPCI File', required: true },
      { key: 'middleware', label: 'NSDL AEPS Middleware File', required: true },
      { key: 'switch', label: 'NSDL AEPS Switch File', required: false },
    ],
    steps: [
      {
        name: 'Merge NPCI & Middleware',
        leftSource: 'npci',
        rightSource: 'middleware',
        leftSuffix: '_npci',
        rightSuffix: '_mware',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'Transaction Amount_npci', rightCol: 'amountTransacted_mware', label: 'Transaction Amount' },
          { leftCol: 'Response Code_npci', rightCol: 'status_mware', label: 'status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Switch',
        leftSource: '_merged',
        rightSource: 'switch',
        rightSuffix: '_switch',
        mergeKey: 'RRN',
        rightMergeCol: 'RRN',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'Transaction Amount_npci', rightCol: 'Transaction Amount_switch', label: 'Transaction Amount' },
          { leftCol: 'Response Code_npci', rightCol: 'Transaction Status_switch', label: 'status' },
        ],
        statusDescCol: 'final_status_description_switch',
        statusCol: 'final_status_switch',
      },
    ],
    outputMatchFile: 'nsdlaepsmatch',
    outputMismatchFile: 'nsdlaepsmismatch',
    finalStatusCol: 'final_status_switch',
  },

  {
    id: 'ippbaeps',
    name: 'IPPB AEPS',
    category: 'aeps',
    apiEndpoint: '/ippbaepsrecon',
    bucket: 'prod-isurecon',
    folder: 'ippbaeps',
    sources: [
      { key: 'npci', label: 'IPPB AEPS NPCI File', required: true },
      { key: 'middleware', label: 'IPPB AEPS Middleware File', required: true },
      { key: 'switch', label: 'IPPB AEPS Switch File', required: true },
      { key: 'wallet', label: 'IPPB AEPS Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge NPCI, Switch & Middleware',
        leftSource: 'npci',
        rightSource: 'switch',
        thirdSource: 'middleware',
        leftSuffix: '_npci',
        rightSuffix: '_switch',
        thirdSuffix: '_mware',
        mergeKey: 'RRN',
        secondMergeKey: 'relatioanlId',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        thirdMergeCol: 'RRN',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'Transaction Status_npci', rightCol: 'Transaction Status_switch', thirdCol: 'status_mware', label: 'Transaction Status' },
          { leftCol: 'Actual Transaction Amount_npci', rightCol: 'Transaction Amount_switch', thirdCol: 'amountTransacted_mware', label: 'Transaction Amount' },
          { leftCol: 'PAN Number_npci', rightCol: 'Card No_switch', thirdCol: 'cardDetails_mware', label: 'Card No New' },
        ],
        statusDescCol: 'final_status_description_mware',
        statusCol: 'final_status_mware',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'relatioanlId',
        rightMergeCol: 'relatioanlId',
        mergeHow: 'left',
        comparisons: [
          { leftCol: 'status_mware', rightCol: 'status_wallet', label: 'Transaction Status' },
          { leftCol: 'amountTransacted_mware', rightCol: 'CreditAmount_wallet', label: 'Transaction Amount' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'ippbaepsmatch',
    outputMismatchFile: 'ippbaepsmismatch',
    finalStatusCol: 'final_status_wallet',
  },

  // ═══════════════════════════════════════════
  // CATEGORY: MATM
  // ═══════════════════════════════════════════

  {
    id: 'matm4way',
    name: 'MATM 4-Way Txn Recon',
    category: 'matm',
    apiEndpoint: '/matm4wayrecon',
    bucket: 'prod-isurecon',
    folder: 'matm',
    sources: [
      { key: 'wallet', label: 'Wallet Report', required: true },
      { key: 'switch', label: 'Switch Report', required: true },
      { key: 'npci', label: 'NPCI Settlement Report', required: true },
      { key: 'nsdl', label: 'NSDL Bank Report', required: true },
    ],
    steps: [
      {
        name: '3-Way Merge (Wallet, Switch & NPCI)',
        leftSource: 'wallet',
        rightSource: 'switch',
        thirdSource: 'npci',
        leftSuffix: '_wallet',
        rightSuffix: '_switch',
        thirdSuffix: '_npci',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        thirdMergeCol: 'RRN',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'Status_wallet', rightCol: 'Status_switch', thirdCol: 'Status_npci', label: 'Status' },
          { leftCol: 'Amount_wallet', rightCol: 'Amount_switch', thirdCol: 'Amount_npci', label: 'Amount' },
        ],
        statusDescCol: 'final_status_description_3way',
        statusCol: 'final_status_3way',
      },
      {
        name: '4th-Way Merge with NSDL',
        leftSource: '_merged',
        rightSource: 'nsdl',
        rightSuffix: '_nsdl',
        mergeKey: 'RRN',
        rightMergeCol: 'RRN',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'Status_wallet', rightCol: 'Status_nsdl', label: 'NSDL Status' },
          { leftCol: 'Amount_wallet', rightCol: 'Amount_nsdl', label: 'NSDL Amount' },
        ],
        statusDescCol: 'final_status_description_nsdl',
        statusCol: 'final_status_nsdl',
      },
    ],
    outputMatchFile: 'matm_4way_matched',
    outputMismatchFile: 'matm_4way_mismatched',
    finalStatusCol: 'final_status_nsdl',
  },

  {
    id: 'matm3way',
    name: 'MATM 3-Way Txn Recon',
    category: 'matm',
    apiEndpoint: '/matm3wayrecon',
    bucket: 'prod-isurecon',
    folder: 'matm',
    sources: [
      { key: 'wallet', label: 'Wallet Report', required: true },
      { key: 'switch', label: 'Switch Report', required: true },
      { key: 'npci', label: 'NPCI Settlement Report', required: true },
    ],
    steps: [
      {
        name: '3-Way Merge (Wallet, Switch & NPCI)',
        leftSource: 'wallet',
        rightSource: 'switch',
        thirdSource: 'npci',
        leftSuffix: '_wallet',
        rightSuffix: '_switch',
        thirdSuffix: '_npci',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        thirdMergeCol: 'RRN',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'Status_wallet', rightCol: 'Status_switch', thirdCol: 'Status_npci', label: 'Status' },
          { leftCol: 'Amount_wallet', rightCol: 'Amount_switch', thirdCol: 'Amount_npci', label: 'Amount' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
    ],
    outputMatchFile: 'matm_3way_matched',
    outputMismatchFile: 'matm_3way_mismatched',
    finalStatusCol: 'final_status',
  },

  {
    id: 'matmcommission',
    name: 'MATM Commission Recon',
    category: 'matm',
    apiEndpoint: '/matmcommissionrecon',
    bucket: 'prod-isurecon',
    folder: 'matm',
    sources: [
      { key: 'wallet', label: 'Wallet Report', required: true },
      { key: 'commission', label: 'Commission Report', required: true },
    ],
    steps: [
      {
        name: '2-Way Merge (Wallet & Commission)',
        leftSource: 'wallet',
        rightSource: 'commission',
        leftSuffix: '_wallet',
        rightSuffix: '_comm',
        mergeKey: 'relationalId',
        leftMergeCol: 'relationalId',
        rightMergeCol: 'relationalId',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'amountTransacted_wallet', rightCol: 'relationalAmount_comm', label: 'Txn Amount' },
          { leftCol: 'commissionAmount_wallet', rightCol: 'amountTransacted_comm', label: 'Commission Amount' },
          { leftCol: 'Status_wallet', rightCol: 'Status_comm', label: 'Status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
    ],
    outputMatchFile: 'matm_commission_matched',
    outputMismatchFile: 'matm_commission_mismatched',
    finalStatusCol: 'final_status',
  },

  {
    id: 'equitasmatm',
    name: 'Equitas MATM',
    category: 'matm',
    apiEndpoint: '/equitasmatmrecon',
    bucket: 'prod-isurecon',
    folder: 'euitasmatm',
    sources: [
      { key: 'bank', label: 'Equitas MATM Bank File', required: true },
      { key: 'internal', label: 'Equitas MATM Internal File', required: true },
      { key: 'wallet', label: 'Equitas Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge Bank & Internal',
        leftSource: 'bank',
        rightSource: 'internal',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'apiTid',
        mergeHow: 'outer',
        useSuffixes: true,
        leftSuffix: '_bank',
        rightSuffix: '_internal',
        comparisons: [
          { leftCol: 'Transaction Amount_bank', rightCol: 'Transaction Amount_internal', label: 'Transaction Amount' },
          { leftCol: 'NPCI_bank', rightCol: 'NPCI_internal', label: 'NPCI' },
          { leftCol: 'CARD No_bank', rightCol: 'CARD No_internal', label: 'CARD No trim' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        mergeKey: 'RRN',
        rightMergeCol: 'apiTid',
        mergeHow: 'outer',
        useSuffixes: true,
        leftSuffix: '_merge',
        rightSuffix: '_wallet',
        comparisons: [
          { leftCol: 'Transaction Amount_internal', rightCol: 'Transaction Amount_wallet', label: 'Transaction Amount' },
          { leftCol: 'Status_wal', rightCol: 'status_wallet', label: 'Status_wal' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'equitasmatm_match_merge',
    outputMismatchFile: 'equitasmatm_mismatch_merge',
    finalStatusCol: 'final_status_wallet',
  },

  {
    id: 'nsdlmatm',
    name: 'NSDL MATM',
    category: 'matm',
    apiEndpoint: '/nsdlmatmrecon',
    bucket: 'prod-isurecon',
    folder: 'nsdlmatm',
    sources: [
      { key: 'npci', label: 'NSDL MATM NPCI File', required: true },
      { key: 'switch', label: 'NSDL MATM Switch File', required: true },
      { key: 'middleware', label: 'NSDL MATM Middleware File', required: true },
      { key: 'wallet', label: 'NSDL MATM Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge NPCI, Switch & Middleware',
        leftSource: 'npci',
        rightSource: 'switch',
        thirdSource: 'middleware',
        leftSuffix: '_npci',
        rightSuffix: '_switch',
        thirdSuffix: '_mware',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        thirdMergeCol: 'RRN',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'Transaction Status_npci', rightCol: 'response_code_switch', thirdCol: 'status_mware', label: 'Transaction Status' },
          { leftCol: 'Actual Transaction Amount_npci', rightCol: 'transaction_amount_switch', thirdCol: 'amountTransacted_mware', label: 'Actual Transaction Amount' },
          { leftCol: 'PAN Number_npci', rightCol: 'Card Number (Masked)_switch', thirdCol: 'referenceNo_mware', label: 'Card No New' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'Id',
        rightMergeCol: 'Id',
        mergeHow: 'left',
        comparisons: [
          { leftCol: 'status_mware', rightCol: 'status_wallet', label: 'Transaction Status' },
          { leftCol: 'amountTransacted_mware', rightCol: 'amountTransacted_wallet', label: 'Actual Transaction Amount' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'nsdlmatmmatch',
    outputMismatchFile: 'nsdlmatmmismatch',
    finalStatusCol: 'final_status_wallet',
  },

  {
    id: 'ippbmatm',
    name: 'IPPB MATM',
    category: 'matm',
    apiEndpoint: '/ippbmatmrecon',
    bucket: 'prod-isurecon',
    folder: 'ippbmatm',
    sources: [
      { key: 'npci', label: 'IPPB MATM NPCI File', required: true },
      { key: 'switch', label: 'IPPB MATM Switch File', required: true },
      { key: 'middleware', label: 'IPPB MATM Middleware File', required: true },
      { key: 'wallet', label: 'IPPB MATM Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge NPCI, Switch & Middleware',
        leftSource: 'npci',
        rightSource: 'switch',
        thirdSource: 'middleware',
        leftSuffix: '_npci',
        rightSuffix: '_switch',
        thirdSuffix: '_mware',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        thirdMergeCol: 'RRN',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'Transaction Status_npci', rightCol: 'response_code_switch', thirdCol: 'status_mware', label: 'Transaction Status' },
          { leftCol: 'Transaction Amount_npci', rightCol: 'transaction_amount_switch', thirdCol: 'amountTransacted_mware', label: 'Transaction Amount' },
          { leftCol: 'Card No New_npci', rightCol: 'Card Number (Masked)_switch', thirdCol: 'cardDetails_mware', label: 'Card No New' },
          { leftCol: 'Username_npci', rightCol: 'Card acceptor name / location_switch', thirdCol: 'userName_mware', label: 'Username' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'relatioanlId',
        rightMergeCol: 'relatioanlId',
        mergeHow: 'left',
        comparisons: [
          { leftCol: 'status_mware', rightCol: 'status_wallet', label: 'Transaction Status' },
          { leftCol: 'amountTransacted_mware', rightCol: 'CreditAmount_wallet', label: 'Transaction Amount' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'ippbmatmmatch',
    outputMismatchFile: 'ippbmatmmismatch',
    finalStatusCol: 'final_status_wallet',
  },

  // ═══════════════════════════════════════════
  // CATEGORY: IMPS
  // ═══════════════════════════════════════════

  {
    id: 'nsdlimps',
    name: 'NSDL IMPS',
    category: 'imps',
    apiEndpoint: '/nsdlimpsrecon',
    bucket: 'impsrecon',
    folder: 'nsdlimps',
    sources: [
      { key: 'npci', label: 'NSDL IMPS NPCI File', required: true },
      { key: 'middleware', label: 'NSDL IMPS Middleware File', required: true },
      { key: 'switch', label: 'NSDL IMPS Switch File', required: true },
      { key: 'wallet', label: 'NSDL IMPS Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge NPCI, Middleware & Switch',
        leftSource: 'npci',
        rightSource: 'middleware',
        thirdSource: 'switch',
        leftSuffix: '_npci',
        rightSuffix: '_mware',
        thirdSuffix: '_switch',
        mergeKey: 'UniqueId',
        leftMergeCol: 'UniqueId',
        rightMergeCol: 'UniqueId',
        thirdMergeCol: 'UniqueId',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'Response Code_npci', rightCol: 'gatewaystatus_mware', thirdCol: 'Switch_Status_switch', label: 'status' },
          { leftCol: 'Transaction Amount_npci', rightCol: 'gatewayamount_mware', thirdCol: 'Transaction_Amount_switch', label: 'Transaction Amount' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'gatewayId',
        rightMergeCol: 'gatewayId',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'gatewaystatus_mware', rightCol: 'gatewaystatus_wallet', label: 'status' },
          { leftCol: 'gatewayamount_mware', rightCol: 'gateway_amount_wallet', label: 'Transaction Amount' },
        ],
        statusDescCol: 'final_status_description_wal',
        statusCol: 'final_status_wal',
      },
    ],
    outputMatchFile: 'nsdlimpsmatch',
    outputMismatchFile: 'nsdlimpsmismatch',
    finalStatusCol: 'final_status_wal',
  },

  {
    id: 'ippbimps',
    name: 'IPPB IMPS',
    category: 'imps',
    apiEndpoint: '/ippbimpsrecon',
    bucket: 'prod-isurecon',
    folder: 'IPPB',
    sources: [
      { key: 'npci', label: 'IPPB NPCI File', required: true },
      { key: 'middleware', label: 'IPPB IMPS Middleware File', required: true },
      { key: 'switch', label: 'IPPB Switch File', required: true },
      { key: 'wallet', label: 'IPPB IMPS Wallet File', required: true },
      { key: 'mware_cashout', label: 'IPPB Cashout Middleware File', required: false },
      { key: 'wallet_cashout', label: 'IPPB Cashout Wallet File', required: false },
      { key: 'dispute', label: 'Dispute File', required: false },
    ],
    steps: [
      {
        name: 'Merge NPCI, Switch & Middleware',
        leftSource: 'npci',
        rightSource: 'switch',
        thirdSource: 'middleware',
        leftSuffix: '_npci',
        rightSuffix: '_switch',
        thirdSuffix: '_mware',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        thirdMergeCol: 'RRN',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'Response Code_npci', rightCol: 'Switch_Status_switch', thirdCol: 'gatewaystatus_mware', label: 'Status' },
          { leftCol: 'Transaction Amount_npci', rightCol: 'Transaction_Amount_switch', thirdCol: 'gatewayamount_mware', label: 'Transaction Amount' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'relationalid',
        rightMergeCol: 'relationalid',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'gatewaystatus_mware', rightCol: 'status_wallet', label: 'Status' },
          { leftCol: 'gatewayamount_mware', rightCol: 'CreditAmount_wallet', label: 'Transaction Amount' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
      {
        name: 'Merge with Cashout Middleware',
        leftSource: '_merged',
        rightSource: 'mware_cashout',
        rightSuffix: '_mwarecashout',
        mergeKey: 'RRN',
        rightMergeCol: 'RRN',
        mergeHow: 'outer',
        optional: true,
        comparisons: [
          { leftCol: 'Response Code_npci', rightCol: 'status_mwarecashout', label: 'Status' },
          { leftCol: 'Transaction Amount_npci', rightCol: 'amountTransacted_mwarecashout', label: 'Transaction Amount' },
        ],
        statusDescCol: 'final_status_description_cashout',
        statusCol: 'final_status_cashout',
      },
      {
        name: 'Merge with Cashout Wallet',
        leftSource: '_merged',
        rightSource: 'wallet_cashout',
        rightSuffix: '_walletcashout',
        mergeKey: 'relationalid2',
        rightMergeCol: 'relationalid2',
        mergeHow: 'outer',
        optional: true,
        comparisons: [
          { leftCol: 'status_mwarecashout', rightCol: 'status_walletcashout', label: 'Status' },
          { leftCol: 'amountTransacted_mwarecashout', rightCol: 'CreditAmount_walletcashout', label: 'Transaction Amount' },
        ],
        statusDescCol: 'final_status_description_walletcashout',
        statusCol: 'final_status_walletcashout',
      },
    ],
    outputMatchFile: 'ippbimpsmatch',
    outputMismatchFile: 'ippbimpsmismatch',
    finalStatusCol: 'final_status_walletcashout',
  },

  // ═══════════════════════════════════════════
  // CATEGORY: BBPS
  // ═══════════════════════════════════════════

  {
    id: 'bbpscou',
    name: 'BBPS COU (Bank of Baroda / BB11)',
    category: 'bbps',
    apiEndpoint: '/bbpscourecon',
    bucket: 'prod-isurecon',
    folder: 'bbpscou',
    sources: [
      { key: 'cbs', label: 'CBS (Finacle) File', required: true },
      { key: 'cou', label: 'COU System (MW & Switch) File', required: true },
      { key: 'npci', label: 'NPCI Settlement File', required: true },
    ],
    steps: [
      {
        name: '3-Way Merge (CBS, COU & NPCI)',
        leftSource: 'cbs',
        rightSource: 'cou',
        thirdSource: 'npci',
        leftSuffix: '_cbs',
        rightSuffix: '_cou',
        thirdSuffix: '_npci',
        mergeKey: 'TxnRefID',
        leftMergeCol: 'TxnRefID',
        rightMergeCol: 'TxnRefID',
        thirdMergeCol: 'TxnRefID',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'Status_cbs', rightCol: 'Status_cou', thirdCol: 'Status_npci', label: 'Status' },
          { leftCol: 'Amount_cbs', rightCol: 'Amount_cou', thirdCol: 'Amount_npci', label: 'Amount' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status_cou',
      },
    ],
    outputMatchFile: 'bbps_cou_match',
    outputMismatchFile: 'bbps_cou_reversal_exception',
    finalStatusCol: 'final_status_cou',
    customClassification: 'classifyBbpsCou',
  },

  {
    id: 'bbpsbou',
    name: 'BBPS BOU Reconciliation',
    category: 'bbps',
    apiEndpoint: '/bbpsbourecon',
    bucket: 'prod-isurecon',
    folder: 'bbpsbou',
    sources: [
      { key: 'npci', label: 'NPCI Settlement File', required: true },
      { key: 'switch', label: 'BOU Switch File', required: true },
      { key: 'mw', label: 'Middleware (MW) File', required: true },
    ],
    steps: [
      {
        name: '3-Way Merge (NPCI, BOU Switch & MW)',
        leftSource: 'npci',
        rightSource: 'switch',
        thirdSource: 'mw',
        leftSuffix: '_npci',
        rightSuffix: '_switch',
        thirdSuffix: '_mw',
        mergeKey: 'TxnRefID',
        leftMergeCol: 'TxnRefID',
        rightMergeCol: 'TxnRefID',
        thirdMergeCol: 'TxnRefID',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'Status_npci', rightCol: 'Status_switch', thirdCol: 'Status_mw', label: 'Status' },
          { leftCol: 'Amount_npci', rightCol: 'Amount_switch', thirdCol: 'Amount_mw', label: 'Amount' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status_bou',
      },
    ],
    outputMatchFile: 'bbps_bou_success',
    outputMismatchFile: 'bbps_bou_pending_failed_exception',
    finalStatusCol: 'final_status_bou',
    customClassification: 'classifyBbpsBou',
  },

  {
    id: 'bbps',
    name: 'NSDL BBPS',
    category: 'bbps',
    apiEndpoint: '/bbpsrecon',
    bucket: 'prod-isurecon',
    folder: 'bbps',
    sources: [
      { key: 'bank', label: 'NSDL Bank File', required: true },
      { key: 'internal', label: 'BBPS Transaction File', required: true },
      { key: 'wallet', label: 'BBPS Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge Bank & Internal',
        leftSource: 'bank',
        rightSource: 'internal',
        leftSuffix: '_bank',
        rightSuffix: '_internal',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        mergeHow: 'left',
        comparisons: [
          { leftCol: 'BILLAMOUNT_bank', rightCol: 'amountTransacted_internal', label: 'amountTransacted' },
          { leftCol: 'TXNSTATUS_bank', rightCol: 'status_internal', label: 'status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'relationalId',
        rightMergeCol: 'relationalId',
        mergeHow: 'left',
        comparisons: [
          { leftCol: 'amountTransacted_internal', rightCol: 'DrAmount_wallet', label: 'amountTransacted' },
          { leftCol: 'status_internal', rightCol: 'status_wallet', label: 'status' },
        ],
        statusDescCol: 'final_status_wallet_description',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'nsdlbbpsmatch',
    outputMismatchFile: 'nsdlbbpsmismatch',
    finalStatusCol: 'final_status_wallet',
  },

  {
    id: 'ippbbbps',
    name: 'IPPB BBPS',
    category: 'bbps',
    apiEndpoint: '/ippbbbpsrecon',
    bucket: 'prod-isurecon',
    folder: 'ippbbbps',
    sources: [
      { key: 'bank', label: 'IPPB Bank File', required: true },
      { key: 'internal', label: 'IPPB BBPS Internal File', required: true },
      { key: 'wallet', label: 'IPPB BBPS Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge Bank & Internal',
        leftSource: 'bank',
        rightSource: 'internal',
        leftSuffix: '_bank',
        rightSuffix: '_internal',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        mergeHow: 'left',
        comparisons: [
          { leftCol: 'BILLAMOUNT_bank', rightCol: 'amountTransacted_internal', label: 'amountTransacted' },
          { leftCol: 'TXNSTATUS_bank', rightCol: 'status_internal', label: 'status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'relationalId',
        rightMergeCol: 'relationalId',
        mergeHow: 'left',
        comparisons: [
          { leftCol: 'amountTransacted_internal', rightCol: 'DrAmount_wallet', label: 'amountTransacted' },
          { leftCol: 'status_internal', rightCol: 'status_wallet', label: 'status' },
        ],
        statusDescCol: 'final_status_wallet_description',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'ippbbbpsmatch',
    outputMismatchFile: 'ippbbbpsmismatch',
    finalStatusCol: 'final_status_wallet',
  },

  // ═══════════════════════════════════════════
  // CATEGORY: RECHARGE
  // ═══════════════════════════════════════════

  {
    id: 'rechargekrack',
    name: 'Recharge Krack',
    category: 'recharge',
    apiEndpoint: '/rechargerecon',
    bucket: 'prod-isurecon',
    folder: 'recharge',
    sources: [
      { key: 'gateway', label: 'Krack Gateway File', required: true },
      { key: 'internal', label: 'Internal Krack File', required: true },
      { key: 'wallet', label: 'Krack Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge Gateway & Internal',
        leftSource: 'gateway',
        rightSource: 'internal',
        leftSuffix: '_krackgateway',
        rightSuffix: '_internal',
        mergeKey: 'Id',
        leftMergeCol: 'Id',
        rightMergeCol: 'Id',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'Status_krackgateway', rightCol: 'status_internal', label: 'status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_krackwallet',
        mergeKey: 'Id',
        rightMergeCol: 'Id',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'status_internal', rightCol: 'apicomment_krackwallet', label: 'status' },
          { leftCol: 'amountTransacted_internal', rightCol: 'amountTransacted_krackwallet', label: 'amountTransacted' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'rechargekrackmatch',
    outputMismatchFile: 'rechargekrackmismatch',
    finalStatusCol: 'final_status_wallet',
  },

  {
    id: 'rechargeeuro',
    name: 'Recharge Euro',
    category: 'recharge',
    apiEndpoint: '/rechargerecon',
    bucket: 'prod-isurecon',
    folder: 'recharge',
    sources: [
      { key: 'gateway', label: 'Euro Gateway File', required: true },
      { key: 'internal', label: 'Internal Euro File', required: true },
      { key: 'wallet', label: 'Euro Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge Gateway & Internal',
        leftSource: 'gateway',
        rightSource: 'internal',
        leftSuffix: '_erngateway',
        rightSuffix: '_internal',
        mergeKey: 'Id',
        leftMergeCol: 'Id',
        rightMergeCol: 'Id',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'Status_erngateway', rightCol: 'status_internal', label: 'status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_eurowallet',
        mergeKey: 'Id',
        rightMergeCol: 'Id',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'status_internal', rightCol: 'Response_eurowallet', label: 'status' },
          { leftCol: 'amountTransacted_internal', rightCol: 'amountTransacted_eurowallet', label: 'amountTransacted' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'rechargeernmatch',
    outputMismatchFile: 'rechargeernmismatch',
    finalStatusCol: 'final_status_wallet',
  },

  // ═══════════════════════════════════════════
  // CATEGORY: UPI
  // ═══════════════════════════════════════════

  {
    id: 'dynamicupi',
    name: 'Dynamic UPI',
    category: 'upi',
    apiEndpoint: '/dynamicupirecon',
    bucket: 'prod-isurecon',
    folder: 'upidynamic',
    sources: [
      { key: 'bank', label: 'UPI Dynamic Bank File', required: true },
      { key: 'internal', label: 'UPI Dynamic Txn File', required: true },
      { key: 'wallet', label: 'UPI Dynamic Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge Bank & Internal',
        leftSource: 'bank',
        rightSource: 'internal',
        leftSuffix: '_bank',
        rightSuffix: '_mware',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        mergeHow: 'left',
        comparisons: [
          { leftCol: 'amount_transaction_bank', rightCol: 'amountTransacted_mware', label: 'amount_transaction' },
          { leftCol: 'Status_bank', rightCol: 'Status_mware', label: 'Status' },
          { leftCol: 'UsernameAPI_bank', rightCol: 'Username_mware', label: 'userNameAPI' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'RRN',
        rightMergeCol: 'apiTid',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'amountTransacted_mware', rightCol: 'amountTransacted_wallet', label: 'amount_transaction' },
          { leftCol: 'Username_mware', rightCol: 'userName_wallet', label: 'userNameAPI' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'upidynamicmatch',
    outputMismatchFile: 'upidynamicmismatch',
    finalStatusCol: 'final_status_wallet',
  },

  {
    id: 'staticupi',
    name: 'Static UPI',
    category: 'upi',
    apiEndpoint: '/staticupirecon',
    bucket: 'prod-isurecon',
    folder: 'upistatic',
    sources: [
      { key: 'bank', label: 'UPI Static Bank File', required: true },
      { key: 'internal', label: 'UPI Static Internal File', required: true },
      { key: 'wallet', label: 'UPI Static Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge Bank & Internal',
        leftSource: 'bank',
        rightSource: 'internal',
        leftSuffix: '_bank',
        rightSuffix: '_mware',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'apiTid',
        mergeHow: 'left',
        comparisons: [
          { leftCol: 'amountTransacted_bank', rightCol: 'amountTransacted_mware', label: 'amountTransacted' },
          { leftCol: 'Status_bank', rightCol: 'Status_mware', label: 'status' },
          { leftCol: 'username_bank', rightCol: 'username_mware', label: 'userName' },
        ],
        statusDescCol: 'final_status_description_bank',
        statusCol: 'final_status_bank_mware',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'relationalId',
        rightMergeCol: 'relationalId',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'amountTransacted_mware', rightCol: 'amountTransacted_wallet', label: 'amountTransacted' },
          { leftCol: 'Status_mware', rightCol: 'Status_wallet', label: 'status' },
          { leftCol: 'username_mware', rightCol: 'userNameAPI_wallet', label: 'userName' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_mware_wallet',
      },
    ],
    outputMatchFile: 'upistaticmatch',
    outputMismatchFile: 'upistaticmismatch',
    finalStatusCol: 'final_status_mware_wallet',
  },

  // ═══════════════════════════════════════════
  // CATEGORY: DMT
  // ═══════════════════════════════════════════

  {
    id: 'airteldmt',
    name: 'Airtel DMT',
    category: 'dmt',
    apiEndpoint: '/airteldmtrecon',
    bucket: 'prod-isurecon',
    folder: 'airteldmt',
    sources: [
      { key: 'bank', label: 'Bank File', required: true },
      { key: 'internal', label: 'Internal File', required: true },
      { key: 'wallet', label: 'Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge Bank & Internal',
        leftSource: 'bank',
        rightSource: 'internal',
        leftSuffix: '_bank',
        rightSuffix: '_internal',
        mergeKey: 'rrn',
        leftMergeCol: 'rrn',
        rightMergeCol: 'rrn',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'Original Amount_bank', rightCol: 'gatewayAmount_internal', label: 'gatewayAmount' },
          { leftCol: 'DR-AMOUNT RRN COUNT 1_bank', rightCol: 'gatewayStatus_internal', label: 'gatewayStatus' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'gatewayId',
        rightMergeCol: 'gatewayId',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'gatewayAmount_internal', rightCol: 'gatewayamount_wallet', label: 'gatewayAmount' },
          { leftCol: 'gatewayStatus_internal', rightCol: 'gatewaystatus_wallet', label: 'wallet_status_2' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'airteldmtmatch',
    outputMismatchFile: 'airteldmtmismatch',
    finalStatusCol: 'final_status_wallet',
  },

  {
    id: 'finodmt',
    name: 'Fino DMT',
    category: 'dmt',
    apiEndpoint: '/finodmtrecon',
    bucket: 'prod-isurecon',
    folder: 'finodmt',
    sources: [
      { key: 'bank', label: 'Bank File', required: true },
      { key: 'internal', label: 'Internal File', required: true },
      { key: 'wallet', label: 'Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge Bank & Internal',
        leftSource: 'bank',
        rightSource: 'internal',
        leftSuffix: '_bank',
        rightSuffix: '_internal',
        mergeKey: 'gatewayId',
        leftMergeCol: 'gatewayId',
        rightMergeCol: 'gatewayId',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'AMOUNT_bank', rightCol: 'gatewayAmount_internal', label: 'gatewayAmount' },
          { leftCol: 'BANK STATUS_bank', rightCol: 'gatewayStatus_internal', label: 'gatewayStatus' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'gatewayId',
        rightMergeCol: 'gatewayId',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'gatewayAmount_internal', rightCol: 'gatewayamount_wallet', label: 'gatewayamount' },
          { leftCol: 'gatewayStatus_internal', rightCol: 'gatewaystatus_wallet', label: 'Status_wal' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'finodmtmatch',
    outputMismatchFile: 'finodmtmismatch',
    finalStatusCol: 'final_status_wallet',
  },

  {
    id: 'nsdldmt',
    name: 'NSDL DMT',
    category: 'dmt',
    apiEndpoint: '/nsdldmtrecon',
    bucket: 'prod-isurecon',
    folder: 'nsdldmt',
    sources: [
      { key: 'bank', label: 'NSDL Bank Statement File', required: true },
      { key: 'internal', label: 'Internal File', required: true },
      { key: 'wallet', label: 'Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge Bank & Internal',
        leftSource: 'bank',
        rightSource: 'internal',
        leftSuffix: '_bank',
        rightSuffix: '_internal',
        mergeKey: 'rrn',
        leftMergeCol: 'rrn',
        rightMergeCol: 'rrn',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'amount_bank', rightCol: 'gatewayAmount_internal', label: 'gatewayAmount' },
          { leftCol: 'status_bank', rightCol: 'gatewayStatus_internal', label: 'status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'gatewayId',
        rightMergeCol: 'gatewayId',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'gatewayAmount_internal', rightCol: 'gatewayamount_wallet', label: 'gatewayAmount' },
          { leftCol: 'gatewayStatus_internal', rightCol: 'gatewaystatus_wallet', label: 'status' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'nsdldmtmatch',
    outputMismatchFile: 'nsdldmtmismatch',
    finalStatusCol: 'final_status_wallet',
  },

  // ═══════════════════════════════════════════
  // CATEGORY: POS / CASHPOINT
  // ═══════════════════════════════════════════

  {
    id: 'pos',
    name: 'POS',
    category: 'pos',
    apiEndpoint: '/posrecon',
    bucket: 'prod-isurecon',
    folder: 'pos',
    sources: [
      { key: 'txn', label: 'Transaction File', required: true },
      { key: 'txndump', label: 'Transaction Dump File', required: true },
      { key: 'wallet', label: 'Wallet File', required: true },
      { key: 'cashout', label: 'Cashout File', required: false },
      { key: 'nodal', label: 'Nodal File', required: false },
    ],
    steps: [
      {
        name: 'Merge Txn & TxnDump',
        leftSource: 'txn',
        rightSource: 'txndump',
        leftSuffix: '_txn',
        rightSuffix: '_txndump',
        mergeKey: 'relationalId',
        leftMergeCol: 'relationalId',
        rightMergeCol: 'relationalId',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'amountTransacted_txn', rightCol: 'Amount_txndump', label: 'amountTransacted' },
          { leftCol: 'status_txn', rightCol: 'status_txndump', label: 'status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'relationalId',
        rightMergeCol: 'relationalId',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'netAmount_txn', rightCol: 'amountTransacted_wallet', label: 'netAmount' },
          { leftCol: 'status_txn', rightCol: 'status_wallet', label: 'status' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
      {
        name: 'Merge Cashout & Nodal',
        leftSource: 'cashout',
        rightSource: 'nodal',
        leftSuffix: '_cashout',
        rightSuffix: '_nodal',
        mergeKey: 'apiTid',
        leftMergeCol: 'apiTid',
        rightMergeCol: 'apiTid',
        mergeHow: 'outer',
        optional: true,
        isSeparateOutput: true,
        comparisons: [
          { leftCol: 'amountTransacted_cashout', rightCol: 'Withdrawl Amt_nodal', label: 'amountTransacted' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
    ],
    outputMatchFile: 'posmatch',
    outputMismatchFile: 'posmismatch',
    finalStatusCol: 'final_status_wallet',
  },

  // ═══════════════════════════════════════════
  // CATEGORY: RBL CASHOUT / PAYOUT
  // ═══════════════════════════════════════════

  {
    id: 'wallet2cashout',
    name: 'Wallet2Cashout',
    category: 'cashout',
    apiEndpoint: '/wallet2cashoutrecon',
    bucket: 'prod-isurecon',
    folder: 'w2cashout',
    sources: [
      { key: 'bank', label: 'Bank File', required: true },
      { key: 'isu1', label: 'ISU1 File', required: true },
      { key: 'isu2', label: 'ISU2 File', required: true },
    ],
    concatSources: { target: 'internal', from: ['isu1', 'isu2'] },
    steps: [
      {
        name: 'Merge Bank & Internal (ISU1+ISU2)',
        leftSource: 'internal',
        rightSource: 'bank',
        leftSuffix: '_internalippb',
        rightSuffix: '_bank',
        mergeKey: 'RRN',
        leftMergeCol: 'apiTid',
        rightMergeCol: 'RRN',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'Withdrawl Amt(INR)_internalippb', rightCol: 'Withdrawl Amt(INR)_bank', label: 'Withdrawl Amt(INR)' },
          { leftCol: 'Status_internalippb', rightCol: 'Status_bank', label: 'Status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
    ],
    outputMatchFile: 'w2cashoutmatch',
    outputMismatchFile: 'w2cashoutmismatch',
    finalStatusCol: 'final_status',
  },

  {
    id: 'w2cashoutimps',
    name: 'W2Cashout IMPS',
    category: 'cashout',
    apiEndpoint: '/wallet2cashoutimps',
    bucket: 'impsrecon',
    folder: 'w2cashout',
    sources: [
      { key: 'bank', label: 'Bank File', required: true },
      { key: 'isu1', label: 'ISU1 File', required: true },
      { key: 'isu2', label: 'ISU2 File', required: true },
    ],
    concatSources: { target: 'internal', from: ['isu1', 'isu2'] },
    steps: [
      {
        name: 'Merge Bank & Internal (ISU1+ISU2)',
        leftSource: 'internal',
        rightSource: 'bank',
        leftSuffix: '_internalippb',
        rightSuffix: '_bank',
        mergeKey: 'RRN',
        leftMergeCol: 'apiTid',
        rightMergeCol: 'RRN',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'Withdrawl Amt(INR)_internalippb', rightCol: 'Withdrawl Amt(INR)_bank', label: 'Withdrawl Amt(INR)' },
          { leftCol: 'Status_internalippb', rightCol: 'Status_bank', label: 'Status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
    ],
    outputMatchFile: 'w2impsmatch',
    outputMismatchFile: 'w2impsmismatch',
    finalStatusCol: 'final_status',
  },

  // ═══════════════════════════════════════════
  // ADDITIONAL PRODUCTS
  // ═══════════════════════════════════════════

  {
    id: 'lic',
    name: 'LIC',
    category: 'bbps',
    apiEndpoint: '/licrecon',
    bucket: 'prod-isurecon',
    folder: 'lic',
    sources: [
      { key: 'txn', label: 'Transaction File', required: true },
      { key: 'retailer', label: 'Retailer File', required: true },
    ],
    steps: [
      {
        name: 'Merge Transaction & Retailer',
        leftSource: 'retailer',
        rightSource: 'txn',
        leftSuffix: '_ret',
        rightSuffix: '_txn',
        mergeKey: 'apiTid',
        leftMergeCol: 'apiTid',
        rightMergeCol: 'apiTid',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'TXNSTATUS_ret', rightCol: 'status_txn', label: 'status' },
          { leftCol: 'TRANSACTIONVALUE_ret', rightCol: 'amountTransacted_txn', label: 'amountTransacted' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
    ],
    outputMatchFile: 'licmatch',
    outputMismatchFile: 'licmismatch',
    finalStatusCol: 'final_status',
  },

  {
    id: 'ippbvirtualbls',
    name: 'IPPB Virtual BLS',
    category: 'imps',
    apiEndpoint: '/ippbvblsrecon',
    bucket: 'prod-isurecon',
    folder: 'ippbvirtualbls',
    sources: [
      { key: 'npci', label: 'NPCI File', required: true },
      { key: 'middleware', label: 'Middleware File', required: true },
      { key: 'switch', label: 'Switch File', required: true },
      { key: 'wallet', label: 'Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge NPCI, Switch & Middleware',
        leftSource: 'npci',
        rightSource: 'switch',
        thirdSource: 'middleware',
        leftSuffix: '_npci',
        rightSuffix: '_switch',
        thirdSuffix: '_mware',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        thirdMergeCol: 'RRN',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'Response Code_npci', rightCol: 'status_switch', thirdCol: 'status_mware', label: 'status' },
          { leftCol: 'Transaction Amount_npci', rightCol: 'Transaction_Amount_switch', thirdCol: 'amount_mware', label: 'Transaction Amount' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'RRN',
        rightMergeCol: 'RRN',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'status_mware', rightCol: 'walletStatus_wallet', label: 'status' },
          { leftCol: 'amount_mware', rightCol: 'walletAmount_wallet', label: 'Transaction Amount' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'ippbvbalmatch',
    outputMismatchFile: 'ippbvbalmismatch',
    finalStatusCol: 'final_status_wallet',
  },

  {
    id: 'prepaidcard',
    name: 'PREPAID CARD',
    category: 'cashout',
    apiEndpoint: '/prepaidcardrecon',
    bucket: 'prod-isurecon',
    folder: 'prepaidcard',
    reconStatus: 'Manual',
    sources: [
      { key: 'issuer', label: 'Card Issuer File', required: true },
      { key: 'internal', label: 'Internal Txn File', required: true },
      { key: 'wallet', label: 'Wallet Ledger File', required: true },
    ],
    steps: [
      {
        name: 'Merge Issuer & Internal',
        leftSource: 'issuer',
        rightSource: 'internal',
        leftSuffix: '_issuer',
        rightSuffix: '_internal',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'Txn_Amount_issuer', rightCol: 'amountTransacted_internal', label: 'Txn Amount' },
          { leftCol: 'Status_issuer', rightCol: 'status_internal', label: 'Status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'RRN',
        rightMergeCol: 'relationalId',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'amountTransacted_internal', rightCol: 'amountTransacted_wallet', label: 'Txn Amount' },
          { leftCol: 'status_internal', rightCol: 'status_wallet', label: 'Status' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'prepaidcard_match',
    outputMismatchFile: 'prepaidcard_mismatch',
    finalStatusCol: 'final_status_wallet',
  },

  {
    id: 'upiacquiring',
    name: 'UPI ACQUIRING',
    category: 'upi',
    apiEndpoint: '/upiacquiringrecon',
    bucket: 'prod-isurecon',
    folder: 'upiacquiring',
    reconStatus: 'Manual',
    sources: [
      { key: 'npci', label: 'NPCI Acquiring Settlement File', required: true },
      { key: 'switch', label: 'Acquiring Switch File', required: true },
      { key: 'wallet', label: 'Merchant Wallet File', required: true },
    ],
    steps: [
      {
        name: '3-Way Merge (NPCI, Switch & Wallet)',
        leftSource: 'npci',
        rightSource: 'switch',
        thirdSource: 'wallet',
        leftSuffix: '_npci',
        rightSuffix: '_switch',
        thirdSuffix: '_wallet',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        thirdMergeCol: 'relationalId',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'Status_npci', rightCol: 'Status_switch', thirdCol: 'status_wallet', label: 'Status' },
          { leftCol: 'Amount_npci', rightCol: 'Amount_switch', thirdCol: 'amountTransacted_wallet', label: 'Amount' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
    ],
    outputMatchFile: 'upi_acquiring_match',
    outputMismatchFile: 'upi_acquiring_mismatch',
    finalStatusCol: 'final_status',
  },

  {
    id: 'cashpoint',
    name: 'Cashpoint',
    category: 'pos',
    apiEndpoint: '/cashpointrecon',
    bucket: 'prod-isurecon',
    folder: 'cashpoint',
    reconStatus: 'Manual',
    sources: [
      { key: 'bank', label: 'Cashpoint Bank Extract', required: true },
      { key: 'middleware', label: 'Middleware Log File', required: true },
      { key: 'wallet', label: 'Wallet Ledger File', required: true },
    ],
    steps: [
      {
        name: '3-Way Merge (Bank, Middleware & Wallet)',
        leftSource: 'bank',
        rightSource: 'middleware',
        thirdSource: 'wallet',
        leftSuffix: '_bank',
        rightSuffix: '_mware',
        thirdSuffix: '_wallet',
        mergeKey: 'relationalId',
        leftMergeCol: 'apiTid',
        rightMergeCol: 'relationalId',
        thirdMergeCol: 'relationalId',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'TxnAmount_bank', rightCol: 'amountTransacted_mware', thirdCol: 'amountTransacted_wallet', label: 'Txn Amount' },
          { leftCol: 'Status_bank', rightCol: 'status_mware', thirdCol: 'status_wallet', label: 'Status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
    ],
    outputMatchFile: 'cashpoint_match',
    outputMismatchFile: 'cashpoint_mismatch',
    finalStatusCol: 'final_status',
  },

  {
    id: 'walletrecon',
    name: 'Wallet Recon',
    category: 'cashout',
    apiEndpoint: '/walletrecon',
    bucket: 'prod-isurecon',
    folder: 'walletrecon',
    reconStatus: 'Manual',
    sources: [
      { key: 'wallet', label: 'System Wallet Ledger File', required: true },
      { key: 'nodal', label: 'Core Bank Nodal Statement', required: true },
      { key: 'mw', label: 'Middleware Log Extract', required: true },
    ],
    steps: [
      {
        name: '3-Way Merge (Wallet, Nodal & MW)',
        leftSource: 'wallet',
        rightSource: 'nodal',
        thirdSource: 'mw',
        leftSuffix: '_wallet',
        rightSuffix: '_nodal',
        thirdSuffix: '_mw',
        mergeKey: 'relationalId',
        leftMergeCol: 'relationalId',
        rightMergeCol: 'relationalId',
        thirdMergeCol: 'relationalId',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'amountTransacted_wallet', rightCol: 'CreditAmount_nodal', thirdCol: 'amountTransacted_mw', label: 'Amount' },
          { leftCol: 'status_wallet', rightCol: 'Status_nodal', thirdCol: 'status_mw', label: 'Status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
    ],
    outputMatchFile: 'wallet_recon_match',
    outputMismatchFile: 'wallet_recon_mismatch',
    finalStatusCol: 'final_status',
  },

  {
    id: 'commissionrecon',
    name: 'COMMISSION RECON',
    category: 'matm',
    apiEndpoint: '/generalcommissionrecon',
    bucket: 'prod-isurecon',
    folder: 'commissionrecon',
    reconStatus: 'Manual',
    sources: [
      { key: 'wallet', label: 'Wallet Ledger File', required: true },
      { key: 'commission', label: 'Commission Statement File', required: true },
    ],
    steps: [
      {
        name: '2-Way Merge (Wallet & Commission)',
        leftSource: 'wallet',
        rightSource: 'commission',
        leftSuffix: '_wallet',
        rightSuffix: '_comm',
        mergeKey: 'relationalId',
        leftMergeCol: 'relationalId',
        rightMergeCol: 'relationalId',
        mergeHow: 'outer',
        comparisons: [
          { leftCol: 'amountTransacted_wallet', rightCol: 'relationalAmount_comm', label: 'Txn Amount' },
          { leftCol: 'commissionAmount_wallet', rightCol: 'amountTransacted_comm', label: 'Commission Amount' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
    ],
    outputMatchFile: 'commission_recon_match',
    outputMismatchFile: 'commission_recon_mismatch',
    finalStatusCol: 'final_status',
  },

  {
    id: 'bobproject',
    name: 'BOB Project',
    category: 'aeps',
    apiEndpoint: '/bobprojectrecon',
    bucket: 'prod-isurecon',
    folder: 'bobproject',
    reconStatus: 'Both Manual & Automation',
    sources: [
      { key: 'switch', label: 'BOB Switch Extract', required: true },
      { key: 'middleware', label: 'Middleware Log File', required: true },
      { key: 'wallet', label: 'Wallet Ledger File', required: true },
    ],
    steps: [
      {
        name: '3-Way Merge (BOB Switch, MW & Wallet)',
        leftSource: 'switch',
        rightSource: 'middleware',
        thirdSource: 'wallet',
        leftSuffix: '_bobswitch',
        rightSuffix: '_mware',
        thirdSuffix: '_wallet',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        thirdMergeCol: 'relationalId',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'Status_bobswitch', rightCol: 'status_mware', thirdCol: 'status_wallet', label: 'Status' },
          { leftCol: 'Amount_bobswitch', rightCol: 'amountTransacted_mware', thirdCol: 'amountTransacted_wallet', label: 'Amount' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
    ],
    outputMatchFile: 'bob_project_match',
    outputMismatchFile: 'bob_project_mismatch',
    finalStatusCol: 'final_status',
  },

  {
    id: 'ippbaepscd',
    name: 'IPPB AEPS CD',
    category: 'aeps',
    apiEndpoint: '/ippbaepscdrecon',
    bucket: 'prod-isurecon',
    folder: 'ippbaepscd',
    reconStatus: 'Manual',
    sources: [
      { key: 'npci', label: 'IPPB AEPS CD NPCI File', required: true },
      { key: 'switch', label: 'IPPB AEPS CD Switch File', required: true },
      { key: 'middleware', label: 'IPPB AEPS CD Middleware File', required: true },
      { key: 'wallet', label: 'IPPB AEPS CD Wallet File', required: true },
    ],
    steps: [
      {
        name: 'Merge NPCI, Switch & Middleware',
        leftSource: 'npci',
        rightSource: 'switch',
        thirdSource: 'middleware',
        leftSuffix: '_npci',
        rightSuffix: '_switch',
        thirdSuffix: '_mware',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        thirdMergeCol: 'RRN',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'Transaction Status_npci', rightCol: 'Transaction Status_switch', thirdCol: 'status_mware', label: 'Transaction Status' },
          { leftCol: 'Actual Transaction Amount_npci', rightCol: 'Transaction Amount_switch', thirdCol: 'amountTransacted_mware', label: 'Transaction Amount' },
        ],
        statusDescCol: 'final_status_description_mware',
        statusCol: 'final_status_mware',
      },
      {
        name: 'Merge with Wallet',
        leftSource: '_merged',
        rightSource: 'wallet',
        rightSuffix: '_wallet',
        mergeKey: 'relatioanlId',
        rightMergeCol: 'relatioanlId',
        mergeHow: 'left',
        comparisons: [
          { leftCol: 'status_mware', rightCol: 'status_wallet', label: 'Transaction Status' },
          { leftCol: 'amountTransacted_mware', rightCol: 'CreditAmount_wallet', label: 'Transaction Amount' },
        ],
        statusDescCol: 'final_status_description_wallet',
        statusCol: 'final_status_wallet',
      },
    ],
    outputMatchFile: 'ippbaepscd_match',
    outputMismatchFile: 'ippbaepscd_mismatch',
    finalStatusCol: 'final_status_wallet',
  },

  {
    id: 'ippbcashout',
    name: 'IPPB cashout',
    category: 'cashout',
    apiEndpoint: '/ippbcashoutrecon',
    bucket: 'prod-isurecon',
    folder: 'ippbcashout',
    reconStatus: 'Both Manual & Automation',
    sources: [
      { key: 'bank', label: 'IPPB Bank Cashout Statement', required: true },
      { key: 'middleware', label: 'IPPB Cashout Middleware File', required: true },
      { key: 'wallet', label: 'IPPB Cashout Wallet File', required: true },
    ],
    steps: [
      {
        name: '3-Way Merge (Bank, MW & Wallet)',
        leftSource: 'bank',
        rightSource: 'middleware',
        thirdSource: 'wallet',
        leftSuffix: '_bank',
        rightSuffix: '_mware',
        thirdSuffix: '_wallet',
        mergeKey: 'RRN',
        leftMergeCol: 'RRN',
        rightMergeCol: 'RRN',
        thirdMergeCol: 'relationalid',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'Withdrawl Amt_bank', rightCol: 'amountTransacted_mware', thirdCol: 'CreditAmount_wallet', label: 'Amount' },
          { leftCol: 'Status_bank', rightCol: 'status_mware', thirdCol: 'status_wallet', label: 'Status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
    ],
    outputMatchFile: 'ippbcashout_match',
    outputMismatchFile: 'ippbcashout_mismatch',
    finalStatusCol: 'final_status',
  },

  {
    id: 'ippbwallet',
    name: 'IPPB Wallet',
    category: 'aeps',
    apiEndpoint: '/ippbwalletrecon',
    bucket: 'prod-isurecon',
    folder: 'ippbwallet',
    reconStatus: 'Manual',
    sources: [
      { key: 'nodal', label: 'IPPB Bank Nodal File', required: true },
      { key: 'wallet', label: 'IPPB Wallet Ledger File', required: true },
      { key: 'mw', label: 'IPPB Middleware Log File', required: true },
    ],
    steps: [
      {
        name: '3-Way Merge (Nodal, Wallet & MW)',
        leftSource: 'nodal',
        rightSource: 'wallet',
        thirdSource: 'mw',
        leftSuffix: '_nodal',
        rightSuffix: '_wallet',
        thirdSuffix: '_mw',
        mergeKey: 'relationalId',
        leftMergeCol: 'relationalId',
        rightMergeCol: 'relationalId',
        thirdMergeCol: 'relationalId',
        mergeHow: 'outer',
        isThreeWay: true,
        comparisons: [
          { leftCol: 'CreditAmount_nodal', rightCol: 'amountTransacted_wallet', thirdCol: 'amountTransacted_mw', label: 'Amount' },
          { leftCol: 'Status_nodal', rightCol: 'status_wallet', thirdCol: 'status_mw', label: 'Status' },
        ],
        statusDescCol: 'final_status_description',
        statusCol: 'final_status',
      },
    ],
    outputMatchFile: 'ippbwallet_match',
    outputMismatchFile: 'ippbwallet_mismatch',
    finalStatusCol: 'final_status',
  },
];

// ─── HELPER FUNCTIONS ───

export function getCategories() {
  return CATEGORIES;
}

export function getProductsByCategory(categoryId) {
  return PRODUCTS.filter(p => p.category === categoryId);
}

export function getProductById(productId) {
  return PRODUCTS.find(p => p.id === productId);
}

export function getCategoryById(categoryId) {
  return CATEGORIES.find(c => c.id === categoryId);
}

export function getAllProducts() {
  return PRODUCTS;
}
